url: "http://achantar.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "A Chantar" # the name of your site, e.g. ACME Corp.

markdown:           kramdown

sass:
  load_paths:
    - _sass
    - node_modules

exclude: 
  - node_modules
  - LICENSE
  - README.md
  - package.json
  - package-lock.json

#plugins:
  #- jekyll-paginate


#deployment
host: 0.0.0.0
